load(":export_only_module_name_test.bzl", "export_only_module_name_test_suite")
load(":javac_encoding_test.bzl", "javac_encoding_test_suite")
load(":javac_jvm_target_test.bzl", "javac_jvm_target_test_suite")
load(":javac_options_test.bzl", "javac_options_test_suite")
load(":javac_warn_test.bzl", "javac_warn_test_suite")
load(":jvm_deps_tests.bzl", "jvm_deps_test_suite")
load(":kotlinc_options_test.bzl", "kotlinc_options_test_suite")
load(":kover_test.bzl", "kover_test_suite")
load(":kt_jvm_binary_env_test.bzl", "kt_jvm_binary_env_test_suite")
load(":plugin_payload_test.bzl", "plugin_payload_test_suite")
load(":sourceless_library_test.bzl", "sourceless_library_test_suite")

export_only_module_name_test_suite(name = "export_only_module_name_tests")

javac_encoding_test_suite(name = "javac_encoding_tests")

javac_jvm_target_test_suite(name = "javac_jvm_target_tests")

javac_options_test_suite(name = "javac_options_tests")

javac_warn_test_suite(name = "javac_warn_tests")

jvm_deps_test_suite(name = "jvm_tests")

kotlinc_options_test_suite(name = "kotlinc_options_tests")

kover_test_suite(name = "kover_tests")

kt_jvm_binary_env_test_suite(name = "kt_jvm_binary_env_tests")

plugin_payload_test_suite(name = "plugin_payload_tests")

sourceless_library_test_suite(name = "sourceless_library_tests")
